#!/bin/bash
set -e

MYSQL_CONFIG="/opt/zbox/etc/mysql/my.cnf"

export PATH=/opt/zbox/:$PATH
if [ "${1:0:1}" == "-" ]; then
  zbox --help
elif [ "$#" == "0" ]; then
  # if the container run firstly
  if [ ! -d "/opt/zbox" -o ! -d "/opt/zbox/app" ]; then
    echo "Installing Zentao version: $ZENTAO_VER ..."
    tar -zxf /tmp/zbox.tar.gz -C /opt/
    # auto location / to /zentao/
    echo "<meta http-equiv=\"refresh\" content=\"0; url=/zentao/\" />" > /opt/zbox/app/htdocs/index.html

    if [[ "${BIND_ADDRESS}" == [fF][aA][lL][sS][eE] ]] && [ -f "${MYSQL_CONFIG}" ]; then
      sed -Ei 's/^bind-address/#&/' ${MYSQL_CONFIG}
    fi

    # add apache http password for adminer
    if [ -n "${ADMINER_USER}" -a -n "${ADMINER_PASSWD}" ]; then
      /opt/zbox/bin/htpasswd -b /opt/zbox/auth/users ${ADMINER_USER} ${ADMINER_PASSWD}
    fi

  elif [ -f "/opt/zbox/app/zentao/VERSION" ]; then

    CURRENT_VER=`cat /opt/zbox/app/zentao/VERSION | sed 's|.stable||g'`
    echo "Current Zentao version: $CURRENT_VER"
    echo "New Zentao version: $ZENTAO_VER"

    if [ $ZENTAO_VER != $CURRENT_VER ]; then
      # upgrade zentao version
      echo "Backuping db, config and upload ..."
      cp -ar /opt/zbox/data/mysql/zentao /opt/
      cp -a /opt/zbox/app/zentao/config/my.php /opt/
      mv /opt/zbox/app/zentao/www/data/upload /opt/
      echo "Installing Zentao version $ZENTAO_VER ..."
      tar -zxf /tmp/zbox.tar.gz -C /opt/
      # auto location / to /zentao/
      echo "<meta http-equiv=\"refresh\" content=\"0; url=/zentao/\" />" > /opt/zbox/app/htdocs/index.html
      echo "Restoring db, config and upload ..."
      rm -rf /opt/zbox/data/mysql/zentao
      rm -rf /opt/zbox/app/zentao/www/data/upload
      mv /opt/zentao /opt/zbox/data/mysql/
      mv /opt/my.php /opt/zbox/app/zentao/config/
      mv /opt/upload /opt/zbox/app/zentao/www/data/
      echo "Prepare for upgrade ..."
      cp /tmp/upgrade.php /opt/zbox/app/zentao/www/
      touch /opt/zbox/app/zentao/www/ok.txt
      echo "Prepared to upgraded."
      echo "Please visit your Zentao url to complete the upgrade task."
    fi

  fi

  # start service and health check
  zbox start
  tail -f /dev/null

else
  exec "$@"
fi
